// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "authentication.proto" (package "authentication", syntax proto3)
// tslint:disable
//
//-- ./proto/authentication.proto
//
//
/// Authentication Service Definitions
///
/// This file contains the service definitions for the authentication grpc 
/// service
///
/// It includes definitions for:
/// - Authentication
/// - Refresh
/// - UpdatePassword
/// - ResetPassword
/// - Register
/// - Logout
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthenticationService } from "./authentication";
import type { LogoutResponse } from "./authentication";
import type { LogoutRequest } from "./authentication";
import type { RegisterRequest } from "./authentication";
import type { ResetPasswordResponse } from "./authentication";
import type { ResetPasswordRequest } from "./authentication";
import type { UpdatePasswordResponse } from "./authentication";
import type { UpdatePasswordRequest } from "./authentication";
import type { RefreshRequest } from "./authentication";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AuthenticationResponse } from "./authentication";
import type { AuthenticationRequest } from "./authentication";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Protobuf service definition
 *
 * @generated from protobuf service authentication.AuthenticationService
 */
export interface IAuthenticationServiceClient {
    /**
     * @generated from protobuf rpc: Authentication(authentication.AuthenticationRequest) returns (authentication.AuthenticationResponse);
     */
    authentication(input: AuthenticationRequest, options?: RpcOptions): UnaryCall<AuthenticationRequest, AuthenticationResponse>;
    /**
     * @generated from protobuf rpc: Refresh(authentication.RefreshRequest) returns (authentication.AuthenticationResponse);
     */
    refresh(input: RefreshRequest, options?: RpcOptions): UnaryCall<RefreshRequest, AuthenticationResponse>;
    /**
     * @generated from protobuf rpc: UpdatePassword(authentication.UpdatePasswordRequest) returns (authentication.UpdatePasswordResponse);
     */
    updatePassword(input: UpdatePasswordRequest, options?: RpcOptions): UnaryCall<UpdatePasswordRequest, UpdatePasswordResponse>;
    /**
     * @generated from protobuf rpc: ResetPassword(authentication.ResetPasswordRequest) returns (authentication.ResetPasswordResponse);
     */
    resetPassword(input: ResetPasswordRequest, options?: RpcOptions): UnaryCall<ResetPasswordRequest, ResetPasswordResponse>;
    /**
     * @generated from protobuf rpc: Register(authentication.RegisterRequest) returns (authentication.AuthenticationResponse);
     */
    register(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, AuthenticationResponse>;
    /**
     * @generated from protobuf rpc: Logout(authentication.LogoutRequest) returns (authentication.LogoutResponse);
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, LogoutResponse>;
}
/**
 * Protobuf service definition
 *
 * @generated from protobuf service authentication.AuthenticationService
 */
export class AuthenticationServiceClient implements IAuthenticationServiceClient, ServiceInfo {
    typeName = AuthenticationService.typeName;
    methods = AuthenticationService.methods;
    options = AuthenticationService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Authentication(authentication.AuthenticationRequest) returns (authentication.AuthenticationResponse);
     */
    authentication(input: AuthenticationRequest, options?: RpcOptions): UnaryCall<AuthenticationRequest, AuthenticationResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthenticationRequest, AuthenticationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Refresh(authentication.RefreshRequest) returns (authentication.AuthenticationResponse);
     */
    refresh(input: RefreshRequest, options?: RpcOptions): UnaryCall<RefreshRequest, AuthenticationResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<RefreshRequest, AuthenticationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePassword(authentication.UpdatePasswordRequest) returns (authentication.UpdatePasswordResponse);
     */
    updatePassword(input: UpdatePasswordRequest, options?: RpcOptions): UnaryCall<UpdatePasswordRequest, UpdatePasswordResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePasswordRequest, UpdatePasswordResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ResetPassword(authentication.ResetPasswordRequest) returns (authentication.ResetPasswordResponse);
     */
    resetPassword(input: ResetPasswordRequest, options?: RpcOptions): UnaryCall<ResetPasswordRequest, ResetPasswordResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ResetPasswordRequest, ResetPasswordResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Register(authentication.RegisterRequest) returns (authentication.AuthenticationResponse);
     */
    register(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, AuthenticationResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterRequest, AuthenticationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Logout(authentication.LogoutRequest) returns (authentication.LogoutResponse);
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, LogoutResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogoutRequest, LogoutResponse>("unary", this._transport, method, opt, input);
    }
}
