// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "utilities.proto" (package "authentication", syntax proto3)
// tslint:disable
//
//-- ./proto/utilities.proto
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UtilitiesService } from "./utilities";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { PingResponse } from "./utilities";
import type { Empty } from "./common";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * The Utilities service definition.
 *
 * @generated from protobuf service authentication.UtilitiesService
 */
export interface IUtilitiesServiceClient {
    /**
     * Sends a ping
     *
     * @generated from protobuf rpc: Ping(authentication.Empty) returns (authentication.PingResponse);
     */
    ping(input: Empty, options?: RpcOptions): UnaryCall<Empty, PingResponse>;
}
/**
 * The Utilities service definition.
 *
 * @generated from protobuf service authentication.UtilitiesService
 */
export class UtilitiesServiceClient implements IUtilitiesServiceClient, ServiceInfo {
    typeName = UtilitiesService.typeName;
    methods = UtilitiesService.methods;
    options = UtilitiesService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Sends a ping
     *
     * @generated from protobuf rpc: Ping(authentication.Empty) returns (authentication.PingResponse);
     */
    ping(input: Empty, options?: RpcOptions): UnaryCall<Empty, PingResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, PingResponse>("unary", this._transport, method, opt, input);
    }
}
