// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "authentication/logins.proto" (package "authentication", syntax proto3)
// tslint:disable
//
//-- ./proto/logins.proto
//
//
/// Authentication logins service definitions
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { loginsService } from "./logins";
import type { LoginsDeleteResponse } from "./logins";
import type { LoginsDeleteRequest } from "./logins";
import type { LoginsUpdateRequest } from "./logins";
import type { LoginsIndexResponse } from "./logins";
import type { LoginsIndexRequest } from "./logins";
import type { LoginsReadRequest } from "./logins";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { LoginsResponse } from "./logins";
import type { LoginsCreateRequest } from "./logins";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Logins service definition (endpoints).
 *
 * @generated from protobuf service authentication.loginsService
 */
export interface IloginsServiceClient {
    /**
     * @generated from protobuf rpc: Create(authentication.LoginsCreateRequest) returns (authentication.LoginsResponse);
     */
    create(input: LoginsCreateRequest, options?: RpcOptions): UnaryCall<LoginsCreateRequest, LoginsResponse>;
    /**
     * @generated from protobuf rpc: Read(authentication.LoginsReadRequest) returns (authentication.LoginsResponse);
     */
    read(input: LoginsReadRequest, options?: RpcOptions): UnaryCall<LoginsReadRequest, LoginsResponse>;
    /**
     * @generated from protobuf rpc: Index(authentication.LoginsIndexRequest) returns (authentication.LoginsIndexResponse);
     */
    index(input: LoginsIndexRequest, options?: RpcOptions): UnaryCall<LoginsIndexRequest, LoginsIndexResponse>;
    /**
     * @generated from protobuf rpc: Update(authentication.LoginsUpdateRequest) returns (authentication.LoginsResponse);
     */
    update(input: LoginsUpdateRequest, options?: RpcOptions): UnaryCall<LoginsUpdateRequest, LoginsResponse>;
    /**
     * @generated from protobuf rpc: Delete(authentication.LoginsDeleteRequest) returns (authentication.LoginsDeleteResponse);
     */
    delete(input: LoginsDeleteRequest, options?: RpcOptions): UnaryCall<LoginsDeleteRequest, LoginsDeleteResponse>;
}
/**
 * Logins service definition (endpoints).
 *
 * @generated from protobuf service authentication.loginsService
 */
export class loginsServiceClient implements IloginsServiceClient, ServiceInfo {
    typeName = loginsService.typeName;
    methods = loginsService.methods;
    options = loginsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Create(authentication.LoginsCreateRequest) returns (authentication.LoginsResponse);
     */
    create(input: LoginsCreateRequest, options?: RpcOptions): UnaryCall<LoginsCreateRequest, LoginsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginsCreateRequest, LoginsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Read(authentication.LoginsReadRequest) returns (authentication.LoginsResponse);
     */
    read(input: LoginsReadRequest, options?: RpcOptions): UnaryCall<LoginsReadRequest, LoginsResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginsReadRequest, LoginsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Index(authentication.LoginsIndexRequest) returns (authentication.LoginsIndexResponse);
     */
    index(input: LoginsIndexRequest, options?: RpcOptions): UnaryCall<LoginsIndexRequest, LoginsIndexResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginsIndexRequest, LoginsIndexResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Update(authentication.LoginsUpdateRequest) returns (authentication.LoginsResponse);
     */
    update(input: LoginsUpdateRequest, options?: RpcOptions): UnaryCall<LoginsUpdateRequest, LoginsResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginsUpdateRequest, LoginsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Delete(authentication.LoginsDeleteRequest) returns (authentication.LoginsDeleteResponse);
     */
    delete(input: LoginsDeleteRequest, options?: RpcOptions): UnaryCall<LoginsDeleteRequest, LoginsDeleteResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginsDeleteRequest, LoginsDeleteResponse>("unary", this._transport, method, opt, input);
    }
}
